// Drizzle ORM Schema Definitions for xG-Vantage
import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  username: text('username').notNull().unique(),
  passwordHash: text('password_hash'),
  displayName: text('display_name'),
  avatarUrl: text('avatar_url'),
  plan: text('plan').default('free'),
  planExpiresAt: text('plan_expires_at'),
  referralCode: text('referral_code').unique(),
  referredBy: text('referred_by'),
  createdAt: text('created_at').default('CURRENT_TIMESTAMP'),
  updatedAt: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const leagues = sqliteTable('leagues', {
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  country: text('country'),
  countryCode: text('country_code'),
  logo: text('logo'),
  flag: text('flag'),
  isActive: integer('is_active').default(1),
  seasonId: integer('season_id'),
  seasonName: text('season_name'),
  bsdId: integer('bsd_id'),
});

export const teams = sqliteTable('teams', {
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  shortName: text('short_name'),
  country: text('country'),
  logo: text('logo'),
  bsdId: integer('bsd_id').unique(),
});

export const teamProfiles = sqliteTable('team_profiles', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  teamId: integer('team_id').references(() => teams.id),
  seasonId: integer('season_id'),
  leagueId: integer('league_id').references(() => leagues.id),
  avgGoalsScored: real('avg_goals_scored'),
  avgGoalsConceded: real('avg_goals_conceded'),
  avgXgFor: real('avg_xg_for'),
  avgXgAgainst: real('avg_xg_against'),
  possession: real('possession'),
  cleanSheetPct: real('clean_sheet_pct'),
  bttsPct: real('btts_pct'),
  over25Pct: real('over_25_pct'),
  homeAvgScored: real('home_avg_scored'),
  homeAvgConceded: real('home_avg_conceded'),
  awayAvgScored: real('away_avg_scored'),
  awayAvgConceded: real('away_avg_conceded'),
  style: text('style'),
  tacticalProfile: text('tactical_profile'),
  preferredFormation: text('preferred_formation'),
  pressIntensity: text('press_intensity'),
  defLine: text('def_line'),
  form: text('form'),
  homeForm: text('home_form'),
  awayForm: text('away_form'),
  updatedAt: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const fixtures = sqliteTable('fixtures', {
  id: integer('id').primaryKey(),
  bsdId: integer('bsd_id').unique(),
  leagueId: integer('league_id').references(() => leagues.id),
  seasonId: integer('season_id'),
  homeTeamId: integer('home_team_id').references(() => teams.id),
  awayTeamId: integer('away_team_id').references(() => teams.id),
  eventDate: text('event_date'),
  status: text('status').default('notstarted'),
  currentMinute: integer('current_minute'),
  period: text('period'),
  homeScore: integer('home_score'),
  awayScore: integer('away_score'),
  homeScoreHt: integer('home_score_ht'),
  awayScoreHt: integer('away_score_ht'),
  roundNumber: integer('round_number'),
  roundName: text('round_name'),
  isLocalDerby: integer('is_local_derby').default(0),
  travelDistanceKm: real('travel_distance_km'),
  weatherCode: integer('weather_code'),
  weatherDesc: text('weather_desc'),
  temperature: real('temperature'),
  windSpeed: real('wind_speed'),
  attendance: integer('attendance'),
  updatedAt: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const predictions = sqliteTable('predictions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  fixtureId: integer('fixture_id').references(() => fixtures.id),
  pickType: text('pick_type').notNull(),
  pickLabel: text('pick_label').notNull(),
  confidence: real('confidence').notNull(),
  tier: text('tier'),
  phantomScore: real('phantom_score'),
  edge: real('edge'),
  homeWinProb: real('home_win_prob'),
  drawProb: real('draw_prob'),
  awayWinProb: real('away_win_prob'),
  over25Prob: real('over_25_prob'),
  under25Prob: real('under_25_prob'),
  bttsYesProb: real('btts_yes_prob'),
  bttsNoProb: real('btts_no_prob'),
  homeXg: real('home_xg'),
  awayXg: real('away_xg'),
  verdict: text('verdict'),
  decisionStack: text('decision_stack'),
  keyReasons: text('key_reasons'),
  tacticalMatchup: text('tactical_matchup'),
  oddsJson: text('odds_json'),
  result: text('result').default('pending'),
  settledAt: text('settled_at'),
  createdAt: text('created_at').default('CURRENT_TIMESTAMP'),
});

export const picks = sqliteTable('picks', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  predictionId: integer('prediction_id').references(() => predictions.id),
  fixtureId: integer('fixture_id').references(() => fixtures.id),
  rank: integer('rank'),
  date: text('date'),
  category: text('category'),
  createdAt: text('created_at').default('CURRENT_TIMESTAMP'),
});

export const accas = sqliteTable('accas', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').references(() => users.id),
  date: text('date'),
  pickIds: text('pick_ids'),
  totalOdds: real('total_odds'),
  status: text('status').default('pending'),
  createdAt: text('created_at').default('CURRENT_TIMESTAMP'),
});

export const trackRecord = sqliteTable('track_record', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  date: text('date'),
  pickType: text('pick_type'),
  total: integer('total'),
  won: integer('won'),
  lost: integer('lost'),
  void: integer('void_count'),
  winRate: real('win_rate'),
  month: text('month'),
});

export const userFavorites = sqliteTable('user_favorites', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').references(() => users.id),
  leagueId: integer('league_id'),
  teamId: integer('team_id'),
  type: text('type'),
});

export const notifications = sqliteTable('notifications', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').references(() => users.id),
  title: text('title'),
  message: text('message'),
  type: text('type'),
  read: integer('read').default(0),
  createdAt: text('created_at').default('CURRENT_TIMESTAMP'),
});

// Extended tables for detailed data
export const fixtureStats = sqliteTable('fixture_stats', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  fixtureId: integer('fixture_id').references(() => fixtures.id).unique(),
  homeTotalShots: integer('home_total_shots').default(0),
  homeShotsOnTarget: integer('home_shots_on_target').default(0),
  homeBallPossession: real('home_ball_possession').default(50),
  homeExpectedGoals: real('home_expected_goals').default(0),
  homeCornerKicks: integer('home_corner_kicks').default(0),
  homeFouls: integer('home_fouls').default(0),
  homeYellowCards: integer('home_yellow_cards').default(0),
  homeRedCards: integer('home_red_cards').default(0),
  homeAttacks: integer('home_attacks').default(0),
  homeDangerousAttacks: integer('home_dangerous_attacks').default(0),
  awayTotalShots: integer('away_total_shots').default(0),
  awayShotsOnTarget: integer('away_shots_on_target').default(0),
  awayBallPossession: real('away_ball_possession').default(50),
  awayExpectedGoals: real('away_expected_goals').default(0),
  awayCornerKicks: integer('away_corner_kicks').default(0),
  awayFouls: integer('away_fouls').default(0),
  awayYellowCards: integer('away_yellow_cards').default(0),
  awayRedCards: integer('away_red_cards').default(0),
  awayAttacks: integer('away_attacks').default(0),
  awayDangerousAttacks: integer('away_dangerous_attacks').default(0),
});

export const fixtureOdds = sqliteTable('fixture_odds', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  fixtureId: integer('fixture_id').references(() => fixtures.id).unique(),
  homeWin: real('home_win'),
  draw: real('draw'),
  awayWin: real('away_win'),
  over15Goals: real('over_15_goals'),
  over25Goals: real('over_25_goals'),
  over35Goals: real('over_35_goals'),
  under15Goals: real('under_15_goals'),
  under25Goals: real('under_25_goals'),
  under35Goals: real('under_35_goals'),
  bttsYes: real('btts_yes'),
  bttsNo: real('btts_no'),
});

export const fixtureLineups = sqliteTable('fixture_lineups', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  fixtureId: integer('fixture_id').references(() => fixtures.id).unique(),
  lineupStatus: text('lineup_status'),
  homeFormation: text('home_formation'),
  awayFormation: text('away_formation'),
  homePlayers: text('home_players'),
  awayPlayers: text('away_players'),
  homeSubstitutes: text('home_substitutes'),
  awaySubstitutes: text('away_substitutes'),
  homeUnavailable: text('home_unavailable'),
  awayUnavailable: text('away_unavailable'),
  homeConfidence: real('home_confidence'),
  awayConfidence: real('away_confidence'),
  updatedAt: text('updated_at'),
});

export const standings = sqliteTable('standings', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  leagueId: integer('league_id'),
  seasonId: integer('season_id'),
  teamId: integer('team_id'),
  teamName: text('team_name'),
  position: integer('position'),
  played: integer('played'),
  won: integer('won'),
  drawn: integer('drawn'),
  lost: integer('lost'),
  gf: integer('gf'),
  ga: integer('ga'),
  gd: integer('gd'),
  pts: integer('pts'),
  xgf: real('xgf'),
  xga: real('xga'),
  xgd: real('xgd'),
  xgGames: integer('xg_games'),
  form: text('form'),
  isLive: integer('is_live').default(0),
});

export const modelWeights = sqliteTable('model_weights', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  modelVersion: text('model_version'),
  poissonWeight: real('poisson_weight').default(0.35),
  eloWeight: real('elo_weight').default(0.25),
  formWeight: real('form_weight').default(0.20),
  styleMatchupWeight: real('style_matchup_weight').default(0.10),
  contextWeight: real('context_weight').default(0.10),
  isActive: integer('is_active').default(1),
  totalPredictions: integer('total_predictions').default(0),
  correctResults: integer('correct_results').default(0),
  resultAccuracy: real('result_accuracy').default(0),
  avgCalibrationError: real('avg_calibration_error').default(0),
  valueEdgeThreshold: real('value_edge_threshold').default(0.05),
  updatedAt: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const teamElo = sqliteTable('team_elo', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  teamId: integer('team_id'),
  leagueId: integer('league_id'),
  seasonId: integer('season_id'),
  eloRating: real('elo_rating').default(1500),
  eloHomeRating: real('elo_home_rating').default(1500),
  eloAwayRating: real('elo_away_rating').default(1500),
  matchesPlayed: integer('matches_played').default(0),
  lastMatchDate: text('last_match_date'),
  updatedAt: text('updated_at').default('CURRENT_TIMESTAMP'),
});
